version: '3.4'

# add back x-aws-pull_credentials to get this working
services:
  api-gateway:
    image: docker_account/odyssey:server-prod
    env_file: ./services/api-gateway/.env.prod
    ports:
      - "8080:8080"
    environment: 
      - GO111MODULE=on
    entrypoint: "go run main.go"
    sysctls:
      - net.ipv4.ip_forward=1

  shopify-scraper:
    image: docker_account/odyssey:scraper
    ports:
      - "5000:5000"
    entrypoint: "python3 server.py"
    env_file: ./services/shopify_scraper/.env
    sysctls:
      - net.ipv4.ip_forward=1
    environment: 
      - ODYSSEY_API_GW_ENDPOINT=https://odysseycommerce.com/api

  client:
    image: docker_account/odyssey:client-prod
    ports:
      - "3000:3000"
    env_file: ./clients/odyssey/.env.docker
  
  nginx:
    image: docker_account/odyssey:nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - shopify-scraper
      - api-gateway
