export const numOfLocations = [0,1,2]

export const progressSteps = ['Your business information', 'Set up your Stripe Account', 'Review your data'];

export const stepHeadingText = ['',
  'Your business information',
  'Set up your Stripe account', 
  'Review your store data',
  'Congratulations! You store is ready to go!',
  'Hmmm...'
];

export const stepSubheadingText = ['Loading...',
  `Welcome! Tell us about your business. The information will help us to get your store ready. You can always change it later in the Business Console.`,

  [`Set up or link your Stripe account so you'll get paid`, 
    `You didn’t fully set up your Stripe account, and this will affect you getting paid. You can set it up later in Business Console. Do you want to finish setting up your Stripe account now?`,
    `Awesome! You can accept payments now. Let's proceed to the last step`
  ],

  `Congratulations! Your store is ready to go! Hitting Complete will take you to Business Console, where you can add and edit the products in detail.`,

  `The world is waiting for your wonderful products. You can manage your store in Business Console.`,
  `Something went wrong.  Please relogin later.`
];

/*
  'Auto Parts and Accessories',
  'Furniture',
  'Floor Coverings',
  'Other Home Furnishings',
  'Appliances and Electronics',
  'Computers',
  'Camera and Photography',
  'Home Centers',
  'Paint and Wall Paper',
  'Hardware',
  'Other Building Materials',
  'Outdoor Power Equipment',
  'Nursery and Garden',
  'Cosmetic and Beauty',
  'Optical Goods',
  'Other Health and Personal Care',
  'Men's Clothing',
  'Women's Clothing',
  'Children's and Infant's Clothing',
  'Family Clothing',
  'Clothing Accessories',
  'Other Apparel',
  'Shoes',
  'Jewelry',
  'Luggage',
  'Sporting Goods',
  'Hobby, Toy, and Game',
  'Sewing and Needlecraft',
  'Musical Instrument',
  'Books',
  'Record, Tape, and CD',
  'Other General Merchandise',
  'Pet and Pet Supply',
  'Art',
  'Other Miscellaneous Retail', 

{code: 'AL', name: 'Alabama'},
{code: 'AK', name: 'Alaska'},
{code: 'AZ', name: 'Arizona'},
{code: 'AR', name: 'Arkansas'},
{code: 'CA', name: 'California'},
{code: 'CO', name: 'Colorado'},
{code: 'CT', name: 'Connecticut'},
{code: 'DE', name: 'Delaware'},
{code: 'DC', name: 'District Of Columbia'},
{code: 'FL', name: 'Florida'},
{code: 'GA', name: 'Georgia'},
{code: 'HI', name: 'Hawaii'},
{code: 'ID', name: 'Idaho'},
{code: 'IL', name: 'Illinois'},
{code: 'IN', name: 'Indiana'},
{code: 'IA', name: 'Iowa'},
{code: 'KS', name: 'Kansas'},
{code: 'KY', name: 'Kentucky'},
{code: 'LA', name: 'Louisiana'},
{code: 'ME', name: 'Maine'},
{code: 'MD', name: 'Maryland'},
{code: 'MA', name: 'Massachusetts'},
{code: 'MI', name: 'Michigan'},
{code: 'MN', name: 'Minnesota'},
{code: 'MS', name: 'Mississippi'},
{code: 'MO', name: 'Missouri'},
{code: 'MT', name: 'Montana'},
{code: 'NE', name: 'Nebraska'},
{code: 'NV', name: 'Nevada'},
{code: 'NH', name: 'New Hampshire'},
{code: 'NJ', name: 'New Jersey'},
{code: 'NM', name: 'New Mexico'},
{code: 'NY', name: 'New York'},
{code: 'NC', name: 'North Carolina'},
{code: 'ND', name: 'North Dakota'},
{code: 'OH', name: 'Ohio'},
{code: 'OK', name: 'Oklahoma'},
{code: 'OR', name: 'Oregon'},
{code: 'PA', name: 'Pennsylvania'},
{code: 'RI', name: 'Rhode Island'},
{code: 'SC', name: 'South Carolina'},
{code: 'SD', name: 'South Dakota'},
{code: 'TN', name: 'Tennessee'},
{code: 'TX', name: 'Texas'},
{code: 'UT', name: 'Utah'},
{code: 'VT', name: 'Vermont'},
{code: 'VA', name: 'Virginia'},
{code: 'WA', name: 'Washington'},
{code: 'WV', name: 'West Virginia'},
{code: 'WI', name: 'Wisconsin'},
{code: 'WY', name: 'Wyoming'},

  {id: '0', gmt:'', useDaylight: '0', value:'', text: 'Select your time zone'}

{id: '1', gmt: 'GMT-10:00', useDaylight: '0', value: '-10', text: '(GMT-10:00) Hawaii'},
{id: '2', gmt: 'GMT-09:00', useDaylight: '1', value: '-9', text: '(GMT-09:00) Alaska'},
{id: '3', gmt: 'GMT-08:00', useDaylight: '1', value: '-8', text: '(GMT-08:00) Pacific Time (US & Canada)'},
{id: '4', gmt: 'GMT-07:00', useDaylight: '0', value: '-7', text: '(GMT-07:00) Arizona'},
{id: '5', gmt: 'GMT-07:00', useDaylight: '1', value: '-7', text: '(GMT-07:00) Mountain Time (US & Canada)'},
{id: '6', gmt: 'GMT-06:00', useDaylight: '1', value: '-6', text: '(GMT-06:00) Central Time (US & Canada)'},
{id: '7', gmt: 'GMT-05:00', useDaylight: '1', value: '-5', text: '(GMT-05:00) Eastern Time (US & Canada)'},
*/