apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: client
    template:
        metadata:
            labels:
                component: client
        spec:
            containers:
                -   name: client
                    # todo change this to the private image
                    image: jjaquez/odyssey:client
                    imagePullPolicy: Always
                    ports:
                        - containerPort: 80
                    env: 
                        -   name: REACT_APP_API_URL
                            value: https://www.odysseycommerce.com/api
                        -   name: REACT_APP_SCRAPER_URL
                            value: https://www.odysseycommerce.com/scraper
                        -   name: REACT_APP_AUTH0_DOMAIN
                            value: odysseycommerce.auth0.com
                        -   name: REACT_APP_AUTH0_CLIENT_ID
                            value: get_your_own
                        -   name: REACT_APP_AUTH0_AUDIENCE
                            value: https://odysseycommerce.com/api

